### ISSUE TITLE
如何删除pub中的cover封面呢？

### ISSUE THREAD

**Issue by null1024-ws** [luost26/academic-homepage#3]
尝试直接注释，发现不行。有什么解决方法吗
![image](https://github.com/luost26/academic-homepage/assets/79917102/1fd26bc5-c889-48dc-808c-7f3c086b88a9)

**Comment by luost26** [comment]
Now publication items without cover images are supported by commenting out the `cover` attribute.

<img width="961" alt="image" src="https://github.com/luost26/academic-homepage/assets/45375360/162ff0a9-7665-4940-a7fa-4fe5ee965c15">

**Comment by luost26** [comment]
The changes are in https://github.com/luost26/academic-homepage/blob/main/_includes/widgets/publication_item.html
You may replace this file in your repo with the latest one
